{"data_mtime": 1670439406, "dep_lines": [1, 1, 1], "dep_prios": [5, 30, 30], "dependencies": ["builtins", "abc", "typing"], "hash": "5ed50c038e144ddac15adefbd637a0142f935eca1b843888fb5d130c7fd63453", "id": "sympy.geometry.exceptions", "ignore_all": true, "interface_hash": "b1784ac4716426f42c0debe3291b7163328f838be116f8c2e0701ed4cac93ee0", "mtime": 1667208446, "options": {"allow_redefinition": false, "allow_untyped_globals": false, "always_false": [], "always_true": [], "bazel": false, "check_untyped_defs": false, "disallow_any_decorated": false, "disallow_any_explicit": false, "disallow_any_expr": false, "disallow_any_generics": false, "disallow_any_unimported": false, "disallow_incomplete_defs": false, "disallow_subclassing_any": false, "disallow_untyped_calls": false, "disallow_untyped_decorators": false, "disallow_untyped_defs": false, "follow_imports": "normal", "follow_imports_for_stubs": false, "ignore_errors": false, "ignore_missing_imports": false, "implicit_reexport": true, "local_partial_types": false, "mypyc": false, "no_implicit_optional": false, "platform": "linux", "plugins": [], "show_none_errors": true, "strict_concatenate": false, "strict_equality": false, "strict_optional": true, "strict_optional_whitelist": null, "warn_no_return": true, "warn_return_any": false, "warn_unreachable": false, "warn_unused_ignores": false}, "path": "/opt/conda/lib/python3.8/site-packages/sympy-1.11.1-py3.8.egg/sympy/geometry/exceptions.py", "plugin_data": null, "size": 131, "suppressed": [], "version_id": "0.960"}